// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAomIX06TJI1J1BVj6OiaVF6pkQpeuMpCQ',
    appId: '1:590572719793:web:1985e3962cf2038883dc90',
    messagingSenderId: '590572719793',
    projectId: 'crud-7db89',
    authDomain: 'crud-7db89.firebaseapp.com',
    storageBucket: 'crud-7db89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKC4ZeQvegWT5s2BG6BcslSfVFBPhrEY',
    appId: '1:590572719793:android:96a8fdf4bfbf294183dc90',
    messagingSenderId: '590572719793',
    projectId: 'crud-7db89',
    storageBucket: 'crud-7db89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdsFzZpEQB_s6rPSX-6OH58BL6boFpnqg',
    appId: '1:590572719793:ios:232b253fccfb59c883dc90',
    messagingSenderId: '590572719793',
    projectId: 'crud-7db89',
    storageBucket: 'crud-7db89.appspot.com',
    iosBundleId: 'com.example.crud06c1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdsFzZpEQB_s6rPSX-6OH58BL6boFpnqg',
    appId: '1:590572719793:ios:e717bfd6fde605a883dc90',
    messagingSenderId: '590572719793',
    projectId: 'crud-7db89',
    storageBucket: 'crud-7db89.appspot.com',
    iosBundleId: 'com.example.crud06c1.RunnerTests',
  );
}
